### ISSUE TITLE
Szöveg újraméretezése

### ISSUE THREAD

**Issue by baracskaidora** [szollingerrajmund/SpaceHunter#63]

**Comment by Benceszalaiii** [comment]
K =2(a+b)
K’= 2(a’+b’)
K’= 2(λa+ λb)
K’/K =  2 λ (a+b)/2(a+b)
K = λ
T = ab
T’ = λa* λb
T = λ2
A = 6T
A’ = 6T’
A = λ2
V = Talap * ma
V’ = λ2Talap * λma
V’ = λ2 * λ
